### ISSUE TITLE
IntegrationContext.getMessageFlowByName() always returns the first flow

### ISSUE THREAD

**Issue by skoolkid** [spring-projects/spring-integration-dsl-groovy#15]
``IntegrationContext.getMessageFlowByName()`` always returns the first flow instead of the named flow.

The problem is the method implementation:

    messageFlows.find {it.name = name}

It should be:

    messageFlows.find {it.name == name}

**Comment by artembilan** [comment]
Thank you for pointing that out!
Have been fixed and pushed to the `master`.
